---
- hosts: sasgridmeta1
  become: yes
  become_user: sasinst

  tasks:
  - name: stop sas services
    shell: |
      cd /usr/local/config/Lev1
      nohup ./sas.servers stop &

- hosts: sasgridnodes
  become: yes
  become_user: sasinst

  tasks:
  - name: stop sas services
    shell: |
      cd /sas/config/Lev1
      nohup ./sas.servers stop &

  - name: kill processes for 41415
    shell: |
      output=$( ps aux | grep '[4]1415' | awk '{print $2}' )
      if [ ! -z "$output" ]
      then
        kill -9 $output
      fi
