---
- hosts: sasgrid1
  become: yes
  become_user: root
  vars_files: 
    -  /tmp/quickstart/playbooks/vars.yml

  tasks:

  - name: copy SAS Depot
    shell: |
      cd /sas
      time aws s3 cp --quiet s3://{{SASSoftwareDepot}}/{{SASSoftwareDepotName}}.tar {{SASSoftwareDepotName}}//
      tar xvf {{SASSoftwareDepotName}}//{{SASSoftwareDepotName}}.tar
      rm {{SASSoftwareDepotName}}//{{SASSoftwareDepotName}}.tar
      time aws s3 cp s3://{{SASPlanFiles}} {{SASSoftwareDepotName}}/plan_files --recursive
      chown -R sasinst:sas {{SASSoftwareDepotName}}
      chmod -R 755 {{SASSoftwareDepotName}}

  - copy:
      src: /tmp/quickstart
      dest: /sas/
