---
- hosts: sas-all
  become: yes
  become_user: root
  vars_files:
    -  /tmp/quickstart/playbooks/vars.yml

  tasks:

  #
  #  Create users on all hosts
  #

  - name: Ensure group "sas" exists
    group:
      name: sas
      gid: 1003
      state: present
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"

  - name: Ensure user "sasinst" exists, set password
    user:
      name: sasinst
      uid: 501
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"

  - name: Ensure user "lsfadmin" exists, set password
    user:
      name: lsfadmin
      uid: 502
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"

  - name: Ensure user "sas" exists, set password
    user:
      name: sas
      uid: 503
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"

  - name: Ensure user "sasdemo" exists, set password
    user:
      name: sasdemo
      uid: 504
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"

  - name: Ensure user "sassrv" exists, set password
    user:
      name: sassrv
      uid: 505
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"

  - name: Ensure user "sastrust" exists, set password
    user:
      name: sastrust
      uid: 506
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"

  - name: Ensure user "sasadm" exists, set password
    user:
      name: sasadm
      uid: 507
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"

  - name: Ensure user "sasevs" exists, set password
    user:
      name: sasevs
      uid: 508
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"

  - name: Ensure user "webanon" exists, set password
    user:
      name: webanon
      uid: 509
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas
    when: "'gpfs-all' in group_names or 'lustre-all' in group_names"
