---
- hosts: sasgridmeta1
  become: yes
  become_user: root
  vars_files:
    -  /tmp/quickstart/playbooks/vars.yml

  tasks:

  - name: Template over response file
    template:
      src: "/tmp/quickstart/playbooks/templates/{{ item }}.j2"
      dest: "/sas/quickstart/playbooks/templates/{{ item }}"
      owner: sasinst
      group: sas
    with_items:
      - midtier_install.txt
      - midtier_config.txt

  - name: Change permissions on script 
    shell: |
      chmod 755 /sas/quickstart/playbooks/templates/sasgridmidtier.sh

- hosts: sasgridmeta1
  become: yes
  become_user: ec2-user
  vars_files:
    -  /tmp/quickstart/playbooks/vars.yml

  tasks:
  - name: Start SAS on SAS Midtier Server
    command: sh /sas/quickstart/playbooks/templates/sasgridmidtier.sh {{SASSoftwareDepotName}} &> /tmp/sasgridmidtier.log
